In [2]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b = a.reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a [ [True, False, True, False, True, False, True, False, True] ]
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# явное указывание типа данных
ar = np.array([1, 2, 3, 4, 5, 6] , "float64")
ar

array([1., 2., 3., 4., 5., 6.])

In [14]:
# можно использовать как приведение типов переменных и целых массивов (при этом возвращается копия исходного массива)
print(np.complex64(10))
b = np.array([1, 2, 3, 4, 5, 6])
print(np.complex64(b))
print(b)

(10+0j)
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]
[1 2 3 4 5 6]


In [30]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11,12]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
a[0]

array([[1, 2],
       [3, 4]])