In [1]:
import numpy as np

In [12]:
s = np.empty((3, 2), dtype=float)

In [13]:
s

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
s = np.eye(10)

In [15]:
s

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
s = np.identity(5)

In [17]:
s

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
s = np.zeros((4, 5))

In [19]:
s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
s = np.ones((3, 9), dtype="int8")

In [21]:
s

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [29]:
s = np.full((5, 7), "*")

In [30]:
s

array([['*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*'],
       ['*', '*', '*', '*', '*', '*', '*']], dtype='<U1')

In [36]:
# из строки
np.mat('1 2 3 4')

matrix([[1, 2, 3, 4]])

In [37]:
np.mat("1 2; 3 4")

matrix([[1, 2],
        [3, 4]])

In [39]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([1, 5, 9])

In [41]:
np.diagflat([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [42]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [46]:
a = np.array( [(1, 2, 3), (3, 4, 5), (6, 7, 8)])
a

array([[1, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [47]:
np.tril(a)

array([[1, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [48]:
np.triu(a)

array([[1, 2, 3],
       [0, 4, 5],
       [0, 0, 8]])

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [51]:
np.cos(np.arange(0, np.pi, 0.1))

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [52]:
np.linspace(1, 3, 3)

array([1., 2., 3.])

In [53]:
np.logspace(1, 3, 3)

array([  10.,  100., 1000.])

In [58]:
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

In [60]:
np.fromiter("hello", dtype="U1")

array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

In [61]:
np.fromstring("1 2 3", dtype="int16", sep = " ")

array([1, 2, 3], dtype=int16)