In [1]:
import numpy as np

In [6]:
a = np.arange(10)

In [8]:
a.shape = 2, 5

In [10]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
b = a.reshape(10)
# b - представление массива a

In [12]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b[0] = -1

In [14]:
b

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [15]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [17]:
a.ravel()

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [18]:
a.shape = 2, 5

In [19]:
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [20]:
a.shape = -1

In [21]:
a

array([-1,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [22]:
a = np.arange(10)

In [23]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a.shape = 2, 5

In [25]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
b = a.T

In [27]:
b

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [28]:
b.shape

(5, 2)

In [31]:
b_2 = b[:, np.newaxis]

In [32]:
b_2.shape

(5, 1, 2)

In [33]:
120*150

18000