In [1]:
import numpy as np

In [12]:
ar = np.arange(25)

In [14]:
ar = ar.reshape(5, 5)

In [15]:
print(ar)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
print(ar[[0, 1, 2, 3, 4],[0, 1, 2, 3, 4]])

[ 0  6 12 18 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])